#!/usr/bin/env python3
from pathlib import Path

p = Path('src/target/riscv64/codegen_function.c')
text = p.read_text()
old = '''    initializer_index = 0U;\n    relocation_index = 0U;\n    emitted_size = 0U;\n    return minic_riscv64_emit_constant_value(file,\n                                             program,\n                                             object,\n                                             object->type,\n                                             &initializer_index,\n                                             &relocation_index,\n                                             &emitted_size) &&\n           initializer_index == object->initializer_count &&\n           relocation_index == object->relocation_count && emitted_size == storage_size;\n}\n\nstatic bool minic_riscv64_emit_file_asm'''
new = '''    initializer_index = 0U;\n    relocation_index = 0U;\n    emitted_size = 0U;\n    {\n        bool emitted;\n        bool complete;\n\n        emitted = minic_riscv64_emit_constant_value(file,\n                                                    program,\n                                                    object,\n                                                    object->type,\n                                                    &initializer_index,\n                                                    &relocation_index,\n                                                    &emitted_size);\n        complete = emitted && initializer_index == object->initializer_count &&\n                   relocation_index == object->relocation_count && emitted_size == storage_size;\n        if (!complete) {\n            (void)fprintf(stderr,\n                          "MINIC_RV64_RECURSIVE_ARRAY_FAIL name=%s emitted=%d init=%zu/%zu rel=%zu/%zu size=%zu/%zu\\n",\n                          object->name,\n                          emitted ? 1 : 0,\n                          initializer_index,\n                          object->initializer_count,\n                          relocation_index,\n                          object->relocation_count,\n                          emitted_size,\n                          storage_size);\n        }\n        return complete;\n    }\n}\n\nstatic bool minic_riscv64_emit_file_asm'''
if text.count(old) != 1:
    raise SystemExit(f'expected recursive array emitter block once, found {text.count(old)}')
p.write_text(text.replace(old, new, 1))
print('materialized temporary RV64 aggregate terminal diagnostic')
