#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[2]
internal = root / "src/frontend/parser_internal.h"
declarator = root / "src/frontend/parser_declarator.c"

text = internal.read_text()
old = '''typedef struct MinicParsedFunctionDeclarator {\n    MinicSourceSpan name_span;\n    MinicParsedAttributeList attributes;\n    MinicType parameter_types[MINIC_MAX_FUNCTION_PARAMETERS];\n    size_t parameter_count;\n    size_t pointer_depth;\n    unsigned int pointer_const_qualifiers;\n    unsigned int pointer_volatile_qualifiers;\n    bool has_name;\n    bool is_variadic;\n} MinicParsedFunctionDeclarator;\n'''
new = '''typedef struct MinicParsedFunctionDeclarator {\n    MinicSourceSpan name_span;\n    MinicParsedAttributeList attributes;\n    MinicType parameter_types[MINIC_MAX_FUNCTION_PARAMETERS];\n    size_t parameter_count;\n    size_t pointer_depth;\n    unsigned int pointer_const_qualifiers;\n    unsigned int pointer_volatile_qualifiers;\n    size_t array_bounds[8];\n    size_t array_dimension_count;\n    unsigned int array_zero_length_mask;\n    bool array_outermost_incomplete;\n    bool has_name;\n    bool is_variadic;\n} MinicParsedFunctionDeclarator;\n'''
if text.count(old) != 1:
    raise SystemExit(f"function declarator struct count={text.count(old)}")
internal.write_text(text.replace(old, new, 1))

text = declarator.read_text()
anchor = '''bool minic_parser_parse_parenthesized_function_declarator(\n    MinicParser *parser,\n    bool require_name,\n    bool require_pointer,\n    MinicParsedFunctionDeclarator *declarator) {\n'''
helper = '''static bool parse_array_bound_allow_zero(MinicParser *parser, size_t *element_count);\n\nstatic bool parse_parenthesized_function_array_suffix(\n    MinicParser *parser, MinicParsedFunctionDeclarator *declarator) {\n    size_t dimension;\n\n    if (parser == NULL || declarator == NULL) {\n        return false;\n    }\n    while (parser->current.kind == MINIC_TOKEN_LBRACKET) {\n        if (declarator->array_dimension_count >=\n            sizeof(declarator->array_bounds) / sizeof(declarator->array_bounds[0])) {\n            minic_parser_error(parser, \"array declarator supports at most eight dimensions\");\n            return false;\n        }\n        dimension = declarator->array_dimension_count;\n        if (!minic_parser_advance(parser)) {\n            return false;\n        }\n        if (parser->current.kind == MINIC_TOKEN_RBRACKET) {\n            if (dimension != 0U || declarator->array_outermost_incomplete) {\n                minic_parser_error(parser, \"only the outermost array dimension may be incomplete\");\n                return false;\n            }\n            declarator->array_outermost_incomplete = true;\n            declarator->array_bounds[dimension] = 0U;\n            if (!minic_parser_advance(parser)) {\n                return false;\n            }\n        } else {\n            if (!parse_array_bound_allow_zero(parser, &declarator->array_bounds[dimension])) {\n                return false;\n            }\n            if (declarator->array_bounds[dimension] == 0U) {\n                declarator->array_zero_length_mask |= 1U << dimension;\n            }\n        }\n        declarator->array_dimension_count += 1U;\n    }\n    return true;\n}\n\nbool minic_parser_parse_parenthesized_function_declarator(\n    MinicParser *parser,\n    bool require_name,\n    bool require_pointer,\n    MinicParsedFunctionDeclarator *declarator) {\n'''
if text.count(anchor) != 1:
    raise SystemExit(f"parenthesized function declarator anchor count={text.count(anchor)}")
text = text.replace(anchor, helper, 1)

old_return = '''    return minic_parser_expect(\n               parser, MINIC_TOKEN_RPAREN, \"expected ')' after function declarator\") &&\n           minic_parser_parse_function_parameter_suffix(parser, declarator);\n}\n\nstatic bool parse_array_bound_allow_zero(MinicParser *parser, size_t *element_count) {\n'''
new_return = '''    return parse_parenthesized_function_array_suffix(parser, declarator) &&\n           minic_parser_expect(\n               parser, MINIC_TOKEN_RPAREN, \"expected ')' after function declarator\") &&\n           minic_parser_parse_function_parameter_suffix(parser, declarator);\n}\n\nstatic bool parse_array_bound_allow_zero(MinicParser *parser, size_t *element_count) {\n'''
if text.count(old_return) != 1:
    raise SystemExit(f"function declarator return count={text.count(old_return)}")
text = text.replace(old_return, new_return, 1)

old_build = '''    pointer_depth = 0U;\n    while (pointer_depth < declarator->pointer_depth) {\n        unsigned int bit;\n\n        if (!minic_type_pointer_to(function_type, &function_type)) {\n            return false;\n        }\n        bit = 1U << pointer_depth;\n        if ((declarator->pointer_const_qualifiers & bit) != 0U &&\n            !minic_type_add_const(function_type, &function_type)) {\n            return false;\n        }\n        if ((declarator->pointer_volatile_qualifiers & bit) != 0U &&\n            !minic_type_add_volatile(function_type, &function_type)) {\n            return false;\n        }\n        pointer_depth += 1U;\n    }\n    *declarator_type = function_type;\n    return true;\n}\n'''
new_build = '''    pointer_depth = 0U;\n    while (pointer_depth < declarator->pointer_depth) {\n        unsigned int bit;\n\n        if (!minic_type_pointer_to(function_type, &function_type)) {\n            return false;\n        }\n        bit = 1U << pointer_depth;\n        if ((declarator->pointer_const_qualifiers & bit) != 0U &&\n            !minic_type_add_const(function_type, &function_type)) {\n            return false;\n        }\n        if ((declarator->pointer_volatile_qualifiers & bit) != 0U &&\n            !minic_type_add_volatile(function_type, &function_type)) {\n            return false;\n        }\n        pointer_depth += 1U;\n    }\n    {\n        size_t dimension = declarator->array_dimension_count;\n\n        while (dimension > 0U) {\n            unsigned int bit;\n\n            dimension -= 1U;\n            bit = 1U << dimension;\n            if (dimension == 0U && declarator->array_outermost_incomplete) {\n                if (!minic_c0_program_add_incomplete_array_type(\n                        parser->program, function_type, &function_type)) {\n                    return false;\n                }\n            } else if ((declarator->array_zero_length_mask & bit) != 0U) {\n                if (!minic_c0_program_add_zero_length_array_type(\n                        parser->program, function_type, &function_type)) {\n                    return false;\n                }\n            } else if (!minic_c0_program_add_array_type(parser->program,\n                                                       function_type,\n                                                       declarator->array_bounds[dimension],\n                                                       &function_type)) {\n                return false;\n            }\n        }\n    }\n    *declarator_type = function_type;\n    return true;\n}\n'''
if text.count(old_build) != 1:
    raise SystemExit(f"function declarator build tail count={text.count(old_build)}")
declarator.write_text(text.replace(old_build, new_build, 1))
