#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[2]
path = root / "src/frontend/parser_function.c"
text = path.read_text()

old_tentative = '''    } else {\n        existing = minic_c0_program_global_object(parser->program, object_id);\n        if (existing == NULL ||\n            !minic_parser_external_object_types_compatible(\n                parser->program, existing->type, object_type) ||\n            (minic_type_is_array(existing->type) &&\n             !minic_parser_merge_external_array_composite_type(\n                 parser->program, existing->type, object_type)) ||\n            !minic_c0_global_object_merge_tentative(parser->program, object_id)) {\n            minic_parser_error(parser, "conflicting external tentative definition");\n            return false;\n        }\n    }\n'''
new_tentative = '''    } else {\n        bool discard_declared_array;\n\n        existing = minic_c0_program_global_object(parser->program, object_id);\n        discard_declared_array =\n            existing != NULL && minic_type_is_array(existing->type) &&\n            minic_type_is_array(object_type) &&\n            existing->type.array_type_id != object_type.array_type_id &&\n            object_type.array_type_id + 1U == parser->program->array_type_count;\n        if (existing == NULL ||\n            !minic_parser_external_object_types_compatible(\n                parser->program, existing->type, object_type) ||\n            (minic_type_is_array(existing->type) &&\n             !minic_parser_merge_external_array_composite_type(\n                 parser->program, existing->type, object_type)) ||\n            !minic_c0_global_object_merge_tentative(parser->program, object_id)) {\n            minic_parser_error(parser, "conflicting external tentative definition");\n            return false;\n        }\n        /* The declaration descriptor is only a parser-side candidate once a canonical\n         * external entity already exists. Keep the canonical descriptor and retire a\n         * newly-created outer array descriptor after its composite information has been\n         * merged, otherwise an incomplete `name[]` redeclaration survives ownerless in\n         * the Program array arena and correctly trips the AST verifier. */\n        if (discard_declared_array &&\n            !minic_c0_program_discard_last_array_type(parser->program, object_type)) {\n            minic_parser_error(parser, "cannot retire transient external array declaration");\n            return false;\n        }\n    }\n'''

old_definition_head = '''static bool parse_external_object_definition(MinicParser *parser,\n                                             MinicType object_type,\n                                             MinicSourceSpan name_span,\n                                             const char *section_name,\n                                             size_t section_name_length,\n                                             bool has_section,\n                                             size_t explicit_alignment,\n                                             MinicSymbolVisibility visibility,\n                                             bool has_visibility) {\n    MinicGlobalObjectId object_id;\n    const MinicGlobalObject *existing;\n'''
new_definition_head = '''static bool parse_external_object_definition(MinicParser *parser,\n                                             MinicType object_type,\n                                             MinicSourceSpan name_span,\n                                             const char *section_name,\n                                             size_t section_name_length,\n                                             bool has_section,\n                                             size_t explicit_alignment,\n                                             MinicSymbolVisibility visibility,\n                                             bool has_visibility) {\n    MinicGlobalObjectId object_id;\n    const MinicGlobalObject *existing;\n    MinicType declared_object_type;\n\n    declared_object_type = object_type;\n'''

old_definition_else = '''    } else {\n        existing = minic_c0_program_global_object(parser->program, object_id);\n        if (existing == NULL ||\n            !minic_parser_external_object_types_compatible(\n                parser->program, existing->type, object_type) ||\n            (minic_type_is_array(existing->type) &&\n             !minic_parser_merge_external_array_composite_type(\n                 parser->program, existing->type, object_type)) ||\n            !minic_c0_global_object_begin_definition(parser->program, object_id)) {\n            minic_parser_error(parser, "conflicting external object definition");\n            return false;\n        }\n    }\n    if (!apply_external_object_metadata(parser,\n'''
new_definition_else = '''    } else {\n        bool discard_declared_array;\n\n        existing = minic_c0_program_global_object(parser->program, object_id);\n        discard_declared_array =\n            existing != NULL && minic_type_is_array(existing->type) &&\n            minic_type_is_array(object_type) &&\n            existing->type.array_type_id != object_type.array_type_id &&\n            object_type.array_type_id + 1U == parser->program->array_type_count;\n        if (existing == NULL ||\n            !minic_parser_external_object_types_compatible(\n                parser->program, existing->type, object_type) ||\n            (minic_type_is_array(existing->type) &&\n             !minic_parser_merge_external_array_composite_type(\n                 parser->program, existing->type, object_type)) ||\n            !minic_c0_global_object_begin_definition(parser->program, object_id)) {\n            minic_parser_error(parser, "conflicting external object definition");\n            return false;\n        }\n        if (discard_declared_array) {\n            object_type = parser->program->global_objects[object_id].type;\n            if (!minic_c0_program_discard_last_array_type(\n                    parser->program, declared_object_type)) {\n                minic_parser_error(parser, "cannot retire transient external array definition");\n                return false;\n            }\n        }\n    }\n    if (!apply_external_object_metadata(parser,\n'''

replacements = [
    (old_tentative, new_tentative, "tentative redeclaration"),
    (old_definition_head, new_definition_head, "definition head"),
    (old_definition_else, new_definition_else, "definition redeclaration"),
]
for old, new, label in replacements:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label} anchor count={count}")
    text = text.replace(old, new, 1)

path.write_text(text)
