#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[2]
path = root / "src/frontend/parser_function.c"
text = path.read_text()

old = '''        if (is_function_pointer_parameter) {\n            if (declarator_has_name && parameter_name_spans != NULL) {\n                parameter_name_spans[*parameter_count] = declarator_name_span;\n            }\n        } else if (parser->current.kind == MINIC_TOKEN_IDENTIFIER) {\n            if (parameter_name_spans != NULL) {\n                parameter_name_spans[*parameter_count] = parser->current.span;\n            }\n            if (!minic_parser_advance(parser)) {\n                return false;\n            }\n        } else if (require_names) {\n            minic_parser_error(parser, "expected parameter name");\n            return false;\n        }\n\n        if (!is_function_pointer_parameter &&\n            !adjust_array_parameter_type(parser, &parameter_type)) {\n            return false;\n        }\n'''
new = '''        if (is_function_pointer_parameter) {\n            if (declarator_has_name && parameter_name_spans != NULL) {\n                parameter_name_spans[*parameter_count] = declarator_name_span;\n            }\n        } else if (parser->current.kind == MINIC_TOKEN_IDENTIFIER) {\n            MinicSourceSpan parameter_name_span;\n\n            parameter_name_span = parser->current.span;\n            if (parameter_name_spans != NULL) {\n                parameter_name_spans[*parameter_count] = parameter_name_span;\n            }\n            if (!minic_parser_advance(parser)) {\n                return false;\n            }\n            if (parser->current.kind == MINIC_TOKEN_LPAREN) {\n                MinicParsedFunctionDeclarator direct_function;\n\n                (void)memset(&direct_function, 0, sizeof(direct_function));\n                direct_function.name_span = parameter_name_span;\n                direct_function.has_name = true;\n                if (!minic_parser_parse_function_parameter_suffix(parser, &direct_function) ||\n                    !minic_parser_build_function_declarator_type(\n                        parser, parameter_type, &direct_function, &parameter_type)) {\n                    if (parser->diagnostic != NULL && parser->diagnostic->message[0] == '\\0') {\n                        minic_parser_error(parser,\n                                           "cannot build direct function parameter declarator");\n                    }\n                    return false;\n                }\n            }\n        } else if (require_names) {\n            minic_parser_error(parser, "expected parameter name");\n            return false;\n        }\n\n        if (!is_function_pointer_parameter &&\n            !adjust_array_parameter_type(parser, &parameter_type)) {\n            return false;\n        }\n'''

if text.count(old) != 1:
    raise SystemExit(f"direct function parameter anchor count={text.count(old)}")
path.write_text(text.replace(old, new, 1))
