#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[2]
path = root / "src/frontend/parser_statement.c"
text = path.read_text()

assignment_anchor = '''static bool add_array_object_element_assignment(MinicParser *parser,\n                                                MinicExpressionId base_id,\n                                                size_t index,\n                                                MinicExpressionId value_id) {\n'''
helper = '''static bool add_zero_initialized_record_lvalue(MinicParser *parser,\n                                               MinicExpressionId base_id,\n                                               MinicSourceSpan initializer_span);\n\nstatic bool add_array_object_element_lvalue(MinicParser *parser,\n                                            MinicExpressionId base_id,\n                                            size_t index,\n                                            MinicSourceSpan span,\n                                            MinicExpressionId *target_id) {\n    const MinicExpression *base;\n    MinicArrayObjectInfo array_info;\n    MinicExpression index_expression;\n    MinicExpression subscript;\n    MinicExpressionId index_id;\n\n    base = minic_c0_program_expression(parser->program, base_id);\n    if (base == NULL || target_id == NULL ||\n        !minic_c0_expression_array_object_info(parser->program, base, &array_info) ||\n        index > (size_t)INT64_MAX || (!array_info.is_incomplete && index >= array_info.element_count)) {\n        minic_parser_error(parser, \"invalid runtime array initializer element\");\n        return false;\n    }\n\n    (void)memset(&index_expression, 0, sizeof(index_expression));\n    index_expression.kind = MINIC_EXPRESSION_INTEGER;\n    index_expression.span = span;\n    index_expression.type = minic_type_unsigned_long();\n    index_expression.value_category = MINIC_VALUE_RVALUE;\n    index_expression.value.integer_value = (int64_t)index;\n    if (!minic_parser_add_expression(parser, &index_expression, &index_id)) {\n        return false;\n    }\n\n    (void)memset(&subscript, 0, sizeof(subscript));\n    subscript.kind = MINIC_EXPRESSION_SUBSCRIPT;\n    subscript.span.begin = base->span.begin;\n    subscript.span.end = span.end;\n    subscript.type = array_info.element_type;\n    subscript.value_category = MINIC_VALUE_LVALUE;\n    subscript.value.subscript.base = base_id;\n    subscript.value.subscript.index = index_id;\n    return minic_parser_add_expression(parser, &subscript, target_id);\n}\n\nstatic bool add_array_object_element_assignment(MinicParser *parser,\n                                                MinicExpressionId base_id,\n                                                size_t index,\n                                                MinicExpressionId value_id) {\n'''
if text.count(assignment_anchor) != 1:
    raise SystemExit(f"assignment anchor count={text.count(assignment_anchor)}")
text = text.replace(assignment_anchor, helper, 1)

old_assignment = '''    const MinicExpression *base;\n    const MinicExpression *value;\n    MinicArrayObjectInfo array_info;\n    MinicExpression index_expression;\n    MinicExpression subscript;\n    MinicExpressionId index_id;\n    MinicExpressionId target_id;\n    MinicSourceSpan base_span;\n    MinicSourceSpan value_span;\n    MinicStatement statement;\n    MinicType element_type;\n\n    base = minic_c0_program_expression(parser->program, base_id);\n    value = minic_c0_program_expression(parser->program, value_id);\n    if (base == NULL || value == NULL ||\n        !minic_c0_expression_array_object_info(parser->program, base, &array_info) ||\n        index > (size_t)INT64_MAX) {\n        minic_parser_error(parser, \"invalid runtime array initializer element\");\n        return false;\n    }\n    base_span = base->span;\n    element_type = array_info.element_type;\n    value_span = value->span;\n    if (minic_type_is_record(element_type)) {\n        minic_parser_error(parser, \"record array initializer elements are not supported yet\");\n        return false;\n    }\n    if (!apply_assignment_conversion(parser, element_type, &value_id) ||\n        !minic_c0_assignment_compatible(parser->program, element_type, value_id)) {\n        minic_parser_error(parser, \"runtime array initializer element type mismatch\");\n        return false;\n    }\n    value = minic_c0_program_expression(parser->program, value_id);\n    if (value == NULL) {\n        minic_parser_error(parser, \"invalid converted runtime array initializer element\");\n        return false;\n    }\n    value_span = value->span;\n\n    (void)memset(&index_expression, 0, sizeof(index_expression));\n    index_expression.kind = MINIC_EXPRESSION_INTEGER;\n    index_expression.span = value_span;\n    index_expression.type = minic_type_unsigned_long();\n    index_expression.value_category = MINIC_VALUE_RVALUE;\n    index_expression.value.integer_value = (int64_t)index;\n    if (!minic_parser_add_expression(parser, &index_expression, &index_id)) {\n        return false;\n    }\n\n    (void)memset(&subscript, 0, sizeof(subscript));\n    subscript.kind = MINIC_EXPRESSION_SUBSCRIPT;\n    subscript.span.begin = base_span.begin;\n    subscript.span.end = value_span.end;\n    subscript.type = element_type;\n    subscript.value_category = MINIC_VALUE_LVALUE;\n    subscript.value.subscript.base = base_id;\n    subscript.value.subscript.index = index_id;\n    if (!minic_parser_add_expression(parser, &subscript, &target_id)) {\n        return false;\n    }\n\n    (void)memset(&statement, 0, sizeof(statement));\n    statement.kind = MINIC_STATEMENT_ASSIGN;\n    statement.span = subscript.span;\n'''
new_assignment = '''    const MinicExpression *base;\n    const MinicExpression *value;\n    MinicArrayObjectInfo array_info;\n    MinicExpressionId target_id;\n    MinicSourceSpan value_span;\n    MinicStatement statement;\n    MinicType element_type;\n\n    base = minic_c0_program_expression(parser->program, base_id);\n    value = minic_c0_program_expression(parser->program, value_id);\n    if (base == NULL || value == NULL ||\n        !minic_c0_expression_array_object_info(parser->program, base, &array_info)) {\n        minic_parser_error(parser, \"invalid runtime array initializer element\");\n        return false;\n    }\n    element_type = array_info.element_type;\n    if (minic_type_is_record(element_type)) {\n        minic_parser_error(parser, \"record array elements require aggregate initialization\");\n        return false;\n    }\n    if (!apply_assignment_conversion(parser, element_type, &value_id) ||\n        !minic_c0_assignment_compatible(parser->program, element_type, value_id)) {\n        minic_parser_error(parser, \"runtime array initializer element type mismatch\");\n        return false;\n    }\n    value = minic_c0_program_expression(parser->program, value_id);\n    if (value == NULL) {\n        minic_parser_error(parser, \"invalid converted runtime array initializer element\");\n        return false;\n    }\n    value_span = value->span;\n    if (!add_array_object_element_lvalue(parser, base_id, index, value_span, &target_id)) {\n        return false;\n    }\n\n    (void)memset(&statement, 0, sizeof(statement));\n    statement.kind = MINIC_STATEMENT_ASSIGN;\n    statement.span = value_span;\n'''
if text.count(old_assignment) != 1:
    raise SystemExit(f"assignment body count={text.count(old_assignment)}")
text = text.replace(old_assignment, new_assignment, 1)

old_zero = '''static bool add_array_object_zero_element(MinicParser *parser,\n                                          MinicExpressionId base_id,\n                                          size_t index,\n                                          MinicSourceSpan initializer_span) {\n    MinicExpression zero;\n    MinicExpressionId zero_id;\n\n    (void)memset(&zero, 0, sizeof(zero));\n    zero.kind = MINIC_EXPRESSION_INTEGER;\n    zero.span = initializer_span;\n    zero.type = minic_type_int();\n    zero.value_category = MINIC_VALUE_RVALUE;\n    zero.value.integer_value = 0;\n    return minic_parser_add_expression(parser, &zero, &zero_id) &&\n           add_array_object_element_assignment(parser, base_id, index, zero_id);\n}\n'''
new_zero = '''static bool add_array_object_zero_element(MinicParser *parser,\n                                          MinicExpressionId base_id,\n                                          size_t index,\n                                          MinicSourceSpan initializer_span) {\n    const MinicExpression *base;\n    MinicArrayObjectInfo array_info;\n    MinicExpression zero;\n    MinicExpressionId element_id;\n    MinicExpressionId zero_id;\n\n    base = minic_c0_program_expression(parser->program, base_id);\n    if (base == NULL ||\n        !minic_c0_expression_array_object_info(parser->program, base, &array_info)) {\n        minic_parser_error(parser, \"invalid runtime array zero initializer target\");\n        return false;\n    }\n    if (minic_type_is_record(array_info.element_type)) {\n        return add_array_object_element_lvalue(\n                   parser, base_id, index, initializer_span, &element_id) &&\n               add_zero_initialized_record_lvalue(parser, element_id, initializer_span);\n    }\n\n    (void)memset(&zero, 0, sizeof(zero));\n    zero.kind = MINIC_EXPRESSION_INTEGER;\n    zero.span = initializer_span;\n    zero.type = minic_type_int();\n    zero.value_category = MINIC_VALUE_RVALUE;\n    zero.value.integer_value = 0;\n    return minic_parser_add_expression(parser, &zero, &zero_id) &&\n           add_array_object_element_assignment(parser, base_id, index, zero_id);\n}\n'''
if text.count(old_zero) != 1:
    raise SystemExit(f"zero helper count={text.count(old_zero)}")
text = text.replace(old_zero, new_zero, 1)

old_preamble = '''    MinicSourceSpan initializer_span;\n    size_t initializer_count;\n\n    if (parser == NULL || element_count == 0U || parser->current.kind != MINIC_TOKEN_LBRACE) {\n'''
new_preamble = '''    const MinicExpression *base;\n    MinicArrayObjectInfo array_info;\n    MinicSourceSpan initializer_span;\n    size_t initializer_count;\n\n    base = minic_c0_program_expression(parser->program, base_id);\n    if (parser == NULL || base == NULL || element_count == 0U ||\n        parser->current.kind != MINIC_TOKEN_LBRACE ||\n        !minic_c0_expression_array_object_info(parser->program, base, &array_info)) {\n'''
# This signature occurs only in parse_fixed_runtime_array_initializer at this point.
if text.count(old_preamble) != 1:
    raise SystemExit(f"fixed array preamble count={text.count(old_preamble)}")
text = text.replace(old_preamble, new_preamble, 1)

old_designated = '''            if (!minic_parser_parse_expression(parser, &value_id, 0U)) {\n                return false;\n            }\n            if (last > first && !runtime_array_multi_range_value_is_repeatable(parser, value_id)) {\n                return false;\n            }\n            for (index = first;; ++index) {\n                if (!add_array_object_element_assignment(parser, base_id, index, value_id)) {\n                    return false;\n                }\n                if (index == last) {\n                    break;\n                }\n            }\n            initializer_count = last + 1U;\n'''
new_designated = '''            if (minic_type_is_record(array_info.element_type)) {\n                MinicExpressionId element_id;\n\n                if (first != last || parser->current.kind != MINIC_TOKEN_LBRACE) {\n                    minic_parser_error(\n                        parser, \"record array range designators require a single braced element\");\n                    return false;\n                }\n                if (!add_array_object_element_lvalue(\n                        parser, base_id, first, parser->current.span, &element_id) ||\n                    !minic_parser_parse_runtime_record_initializer(parser, element_id)) {\n                    return false;\n                }\n            } else {\n                if (!minic_parser_parse_expression(parser, &value_id, 0U)) {\n                    return false;\n                }\n                if (last > first &&\n                    !runtime_array_multi_range_value_is_repeatable(parser, value_id)) {\n                    return false;\n                }\n                for (index = first;; ++index) {\n                    if (!add_array_object_element_assignment(parser, base_id, index, value_id)) {\n                        return false;\n                    }\n                    if (index == last) {\n                        break;\n                    }\n                }\n            }\n            initializer_count = last + 1U;\n'''
if text.count(old_designated) != 1:
    raise SystemExit(f"designated array body count={text.count(old_designated)}")
text = text.replace(old_designated, new_designated, 1)

old_positional = '''        } else {\n            if (initializer_count >= element_count) {\n                minic_parser_error(parser, \"too many runtime array initializer elements\");\n                return false;\n            }\n            if (!minic_parser_parse_expression(parser, &value_id, 0U) ||\n                !add_array_object_element_assignment(\n                    parser, base_id, initializer_count, value_id)) {\n                return false;\n            }\n            initializer_count += 1U;\n        }\n'''
new_positional = '''        } else {\n            if (initializer_count >= element_count) {\n                minic_parser_error(parser, \"too many runtime array initializer elements\");\n                return false;\n            }\n            if (minic_type_is_record(array_info.element_type)) {\n                MinicExpressionId element_id;\n\n                if (parser->current.kind != MINIC_TOKEN_LBRACE) {\n                    minic_parser_error(parser,\n                                       \"runtime record array element requires braces\");\n                    return false;\n                }\n                if (!add_array_object_element_lvalue(parser,\n                                                     base_id,\n                                                     initializer_count,\n                                                     parser->current.span,\n                                                     &element_id) ||\n                    !minic_parser_parse_runtime_record_initializer(parser, element_id)) {\n                    return false;\n                }\n            } else if (!minic_parser_parse_expression(parser, &value_id, 0U) ||\n                       !add_array_object_element_assignment(\n                           parser, base_id, initializer_count, value_id)) {\n                return false;\n            }\n            initializer_count += 1U;\n        }\n'''
if text.count(old_positional) != 1:
    raise SystemExit(f"positional array body count={text.count(old_positional)}")
text = text.replace(old_positional, new_positional, 1)

path.write_text(text)
