from patch_core_m26_lib import insert_before, replace_once

# Core IR instruction vocabulary: keep it compact and architecture-neutral.
replace_once(
    'src/core/core_ir.h',
    '''    MINIC_CORE_INSTRUCTION_INTEGER_ADD,\n    MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND,\n    MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR,\n    MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_LEFT,\n    MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_RIGHT,\n    MINIC_CORE_INSTRUCTION_SCALAR_EQUAL,\n''',
    '''    MINIC_CORE_INSTRUCTION_INTEGER_ADD,\n    MINIC_CORE_INSTRUCTION_INTEGER_SUBTRACT,\n    MINIC_CORE_INSTRUCTION_INTEGER_MULTIPLY,\n    MINIC_CORE_INSTRUCTION_INTEGER_DIVIDE,\n    MINIC_CORE_INSTRUCTION_INTEGER_REMAINDER,\n    MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND,\n    MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_XOR,\n    MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR,\n    MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_LEFT,\n    MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_RIGHT,\n    MINIC_CORE_INSTRUCTION_INTEGER_LESS,\n    MINIC_CORE_INSTRUCTION_SCALAR_EQUAL,\n''')

# Core verifier: same-typed integer arithmetic/bitwise family plus an int-valued less-than.
replace_once(
    'src/core/core_ir.c',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_ADD:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR:\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_ADD:\n    case MINIC_CORE_INSTRUCTION_INTEGER_SUBTRACT:\n    case MINIC_CORE_INSTRUCTION_INTEGER_MULTIPLY:\n    case MINIC_CORE_INSTRUCTION_INTEGER_DIVIDE:\n    case MINIC_CORE_INSTRUCTION_INTEGER_REMAINDER:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_XOR:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR:\n''')
insert_before(
    'src/core/core_ir.c',
    '''    case MINIC_CORE_INSTRUCTION_SCALAR_EQUAL:\n        if (!instruction_result_is_valid(function, instruction) ||\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_LESS:\n        if (!instruction_result_is_valid(function, instruction) ||\n            !minic_type_equal(instruction->type, minic_type_int()) ||\n            instruction->value.binary.left >= function->value_count ||\n            instruction->value.binary.right >= function->value_count ||\n            !available_values[instruction->value.binary.left] ||\n            !available_values[instruction->value.binary.right]) {\n            return false;\n        }\n        left = &function->values[instruction->value.binary.left];\n        right = &function->values[instruction->value.binary.right];\n        return minic_type_is_integer(left->type) && minic_type_equal(left->type, right->type);\n''')

# Core dump names are intentionally semantic, not target mnemonics.
insert_before(
    'src/core/core_ir.c',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND:\n        return fprintf(output,\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_SUBTRACT:\n        return fprintf(output,\n                       "  %%%" PRIu32 " = sub.int %%%" PRIu32 ", %%%" PRIu32 "\\n",\n                       instruction->result,\n                       instruction->value.binary.left,\n                       instruction->value.binary.right) >= 0;\n    case MINIC_CORE_INSTRUCTION_INTEGER_MULTIPLY:\n        return fprintf(output,\n                       "  %%%" PRIu32 " = mul.int %%%" PRIu32 ", %%%" PRIu32 "\\n",\n                       instruction->result,\n                       instruction->value.binary.left,\n                       instruction->value.binary.right) >= 0;\n    case MINIC_CORE_INSTRUCTION_INTEGER_DIVIDE:\n        return fprintf(output,\n                       "  %%%" PRIu32 " = div.int %%%" PRIu32 ", %%%" PRIu32 "\\n",\n                       instruction->result,\n                       instruction->value.binary.left,\n                       instruction->value.binary.right) >= 0;\n    case MINIC_CORE_INSTRUCTION_INTEGER_REMAINDER:\n        return fprintf(output,\n                       "  %%%" PRIu32 " = rem.int %%%" PRIu32 ", %%%" PRIu32 "\\n",\n                       instruction->result,\n                       instruction->value.binary.left,\n                       instruction->value.binary.right) >= 0;\n''')
insert_before(
    'src/core/core_ir.c',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR:\n        return fprintf(output,\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_XOR:\n        return fprintf(output,\n                       "  %%%" PRIu32 " = xor.int %%%" PRIu32 ", %%%" PRIu32 "\\n",\n                       instruction->result,\n                       instruction->value.binary.left,\n                       instruction->value.binary.right) >= 0;\n''')
insert_before(
    'src/core/core_ir.c',
    '''    case MINIC_CORE_INSTRUCTION_SCALAR_EQUAL:\n        return fprintf(output,\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_LESS:\n        return fprintf(output,\n                       "  %%%" PRIu32 " = lt.int %%%" PRIu32 ", %%%" PRIu32 "\\n",\n                       instruction->result,\n                       instruction->value.binary.left,\n                       instruction->value.binary.right) >= 0;\n''')

# RV64 backend coverage. These map directly to scalar integer ISA operations.
replace_once(
    'src/target/riscv64/core_codegen.c',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_ADD:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR:\n    case MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_LEFT:\n    case MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_RIGHT:\n    case MINIC_CORE_INSTRUCTION_SCALAR_EQUAL:\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_ADD:\n    case MINIC_CORE_INSTRUCTION_INTEGER_SUBTRACT:\n    case MINIC_CORE_INSTRUCTION_INTEGER_MULTIPLY:\n    case MINIC_CORE_INSTRUCTION_INTEGER_DIVIDE:\n    case MINIC_CORE_INSTRUCTION_INTEGER_REMAINDER:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_XOR:\n    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR:\n    case MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_LEFT:\n    case MINIC_CORE_INSTRUCTION_INTEGER_SHIFT_RIGHT:\n    case MINIC_CORE_INSTRUCTION_INTEGER_LESS:\n    case MINIC_CORE_INSTRUCTION_SCALAR_EQUAL:\n''')
insert_before(
    'src/target/riscv64/core_codegen.c',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_AND:\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_SUBTRACT:\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n            !load_core_value(file, frame, instruction->value.binary.right, "t1") ||\n            fprintf(file, "  sub t0, t0, t1\\n") < 0 ||\n            !minic_riscv64_emit_integer_conversion_for_program(\n                file, program, instruction->type, "t0")) {\n            return false;\n        }\n        return store_core_value(file, frame, instruction->result, "t0");\n    case MINIC_CORE_INSTRUCTION_INTEGER_MULTIPLY:\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n            !load_core_value(file, frame, instruction->value.binary.right, "t1") ||\n            fprintf(file, "  mul t0, t0, t1\\n") < 0 ||\n            !minic_riscv64_emit_integer_conversion_for_program(\n                file, program, instruction->type, "t0")) {\n            return false;\n        }\n        return store_core_value(file, frame, instruction->result, "t0");\n    case MINIC_CORE_INSTRUCTION_INTEGER_DIVIDE:\n    case MINIC_CORE_INSTRUCTION_INTEGER_REMAINDER: {\n        MinicType effective_type;\n        const char *opcode;\n\n        if (!minic_c0_type_effective_integer_type(program, instruction->type, &effective_type)) {\n            return false;\n        }\n        if (instruction->kind == MINIC_CORE_INSTRUCTION_INTEGER_DIVIDE) {\n            opcode = minic_type_is_unsigned_integer(effective_type) ? "divu" : "div";\n        } else {\n            opcode = minic_type_is_unsigned_integer(effective_type) ? "remu" : "rem";\n        }\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n            !load_core_value(file, frame, instruction->value.binary.right, "t1") ||\n            fprintf(file, "  %s t0, t0, t1\\n", opcode) < 0 ||\n            !minic_riscv64_emit_integer_conversion_for_program(\n                file, program, instruction->type, "t0")) {\n            return false;\n        }\n        return store_core_value(file, frame, instruction->result, "t0");\n    }\n''')
insert_before(
    'src/target/riscv64/core_codegen.c',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_OR:\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_BITWISE_XOR:\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n            !load_core_value(file, frame, instruction->value.binary.right, "t1") ||\n            fprintf(file, "  xor t0, t0, t1\\n") < 0 ||\n            !minic_riscv64_emit_integer_conversion_for_program(\n                file, program, instruction->type, "t0")) {\n            return false;\n        }\n        return store_core_value(file, frame, instruction->result, "t0");\n''')
insert_before(
    'src/target/riscv64/core_codegen.c',
    '''    case MINIC_CORE_INSTRUCTION_SCALAR_EQUAL:\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n''',
    '''    case MINIC_CORE_INSTRUCTION_INTEGER_LESS: {\n        MinicType effective_type;\n        const char *opcode;\n\n        if (instruction->value.binary.left >= function->value_count ||\n            !minic_c0_type_effective_integer_type(\n                program, function->values[instruction->value.binary.left].type, &effective_type)) {\n            return false;\n        }\n        opcode = minic_type_is_unsigned_integer(effective_type) ? "sltu" : "slt";\n        if (!load_core_value(file, frame, instruction->value.binary.left, "t0") ||\n            !load_core_value(file, frame, instruction->value.binary.right, "t1") ||\n            fprintf(file, "  %s t0, t0, t1\\n", opcode) < 0) {\n            return false;\n        }\n        return store_core_value(file, frame, instruction->result, "t0");\n    }\n''')
