#!/bin/sh
set -eu

python3 tools/dev/pr75-signed-char.py
python3 tools/dev/pr75-incomplete-extern-array.py
python3 tools/dev/pr75-incomplete-array-verifier.py
python3 tools/dev/pr75-volatile-qualifier.py
python3 tools/dev/pr75-pointer-volatile-qualifier.py
python3 tools/dev/pr75-array-bound-sizeof.py
python3 tools/dev/pr75-array-bound-sizeof-string.py
python3 tools/dev/pr75-array-bound-enum.py
python3 tools/dev/pr75-array-bound-casts.py
python3 tools/dev/pr75-comma-operator.py
python3 tools/dev/pr75-top-level-comma-conditions.py
python3 tools/dev/pr75-cast-type-classifier.py
python3 tools/dev/pr75-extern-function-declarations.py
python3 tools/dev/pr75-anonymous-record-type-specifiers.py
python3 tools/dev/pr75-union-local-declaration.py
python3 tools/dev/pr75-enum-typedef.py
python3 tools/dev/pr75-enum-constant-expressions.py
python3 tools/dev/pr75-integer-constant-bitwise.py
python3 tools/dev/pr75-unsigned-64-literals.py
python3 tools/dev/pr75-builtin-va-list.py
python3 tools/dev/pr75-restrict-qualifier.py
python3 tools/dev/pr75-gnu-function-attributes.py
python3 tools/dev/pr75-record-forward-declarations.py
python3 tools/dev/pr75-record-top-level-dispatch.py
python3 tools/dev/pr75-record-multi-declarators.py
python3 tools/dev/pr75-record-multidimensional-arrays.py
python3 tools/dev/pr75-record-array-identity.py
python3 tools/dev/pr75-pointer-compound-subtraction.py
python3 tools/dev/pr75-builtin-offsetof.py
python3 tools/dev/pr75-offsetof-constant-expression.py
python3 tools/dev/pr75-record-field-alignment.py
python3 tools/dev/pr75-pointer-integer-casts.py
python3 tools/dev/pr75-record-assignment-expression.py
python3 tools/dev/pr75-compound-assignment-expressions.py
python3 tools/dev/pr75-for-expression-initializers.py
python3 tools/dev/pr75-for-comma-initializers.py
python3 tools/dev/pr75-remainder-assignment.py
python3 tools/dev/pr75-mixed-double-arithmetic.py
python3 tools/dev/pr75-floating-compound-assignments.py
python3 tools/dev/pr75-conditional-pointer-qualifiers.py
python3 tools/dev/pr75-stack-arguments.py
python3 tools/dev/pr75-static-local-record-initializers.py
python3 tools/dev/pr75-static-record-array-initializers.py
python3 tools/dev/pr75-static-nested-record-initializers.py
python3 tools/dev/pr75-static-record-compat.py
python3 tools/dev/pr75-static-local-scalars.py
python3 tools/dev/pr75-static-local-inferred-arrays.py
python3 tools/dev/pr75-static-local-pointer-arrays.py
python3 tools/dev/pr75-static-local-fixed-array-initializers.py
python3 tools/dev/pr75-external-integer-array-initializers.py
python3 tools/dev/pr75-external-pointer-array-initializers.py
python3 tools/dev/pr75-static-inferred-char-arrays.py
python3 tools/dev/pr75-prefix-update-expressions.py
python3 tools/dev/pr75-function-designator-calls.py
python3 tools/dev/pr75-function-address-expressions.py
python3 tools/dev/pr75-gnu-function-asm-labels.py
python3 tools/dev/pr75-gnu-declaration-visibility.py
python3 tools/dev/pr75-visible-extern-arrays.py
printf '%s\n' 'staged Lua discovery semantics'
