#!/bin/sh
set -eu

sh tools/dev/pr75-focused.sh
sh tests/compiler/c0/run-preprocessed-line-markers.sh
sh tests/compiler/c0/run-gnu-signed-keyword.sh
sh tests/compiler/c0/run-gnu-int128-type.sh
sh tests/compiler/c0/run-bool-semantics.sh
sh tests/compiler/c0/run-typeof-generic.sh
sh tests/compiler/c0/run-gnu-typedef-redundant-aligned.sh
sh tests/compiler/c0/run-gnu-record-alignment.sh
sh tests/compiler/c0/run-gnu-empty-records.sh
sh tests/compiler/c0/run-gnu-extension-prefix-declarations.sh
sh tests/compiler/c0/run-gnu-prefix-function-attributes.sh
sh tests/compiler/c0/run-gnu-format-cold-attributes.sh
sh tests/compiler/c0/run-anonymous-record-members.sh
sh tests/compiler/c0/run-block-scope-extern-function-attributes.sh
sh tests/compiler/c0/run-gnu-void-pointer-arithmetic.sh
sh tests/compiler/c0/run-gnu-statement-expression.sh
sh tests/compiler/c0/run-gnu-statement-record-value.sh
sh tests/compiler/c0/run-gnu-static-local-implicit-zero.sh
sh tests/compiler/c0/run-gnu-top-level-empty-declaration.sh
sh tests/compiler/c0/run-gnu-local-label-address.sh
sh tests/compiler/c0/run-gnu-inline-asm-fence.sh
sh tests/compiler/c0/run-gnu-typeof-local-declaration.sh
sh tests/compiler/c0/run-gnu-inline-asm-readwrite-output.sh
sh tests/compiler/c0/run-gnu-inline-asm-operands.sh
sh tests/compiler/c0/run-gnu-inline-asm-named-operands.sh
sh tests/compiler/c0/run-gnu-inline-asm-goto.sh
sh tests/compiler/c0/run-gnu-fixed-register-bindings.sh
sh tests/compiler/c0/run-gnu-compiletime-selection-builtins.sh
sh tests/compiler/c0/run-gnu-builtin-constant-p.sh
sh tests/compiler/c0/run-gnu-builtin-object-size.sh
sh tests/compiler/c0/run-gnu-call-frame-address.sh
sh tests/compiler/c0/run-gnu-pointer-sign-call-conversion.sh
sh tests/compiler/c0/run-static-assert-declaration.sh
sh tests/compiler/c0/run-gnu-choose-expr-bitfield.sh
sh tests/compiler/c0/run-builtin-clzll.sh
sh tests/compiler/c0/run-alignof-type-query.sh
sh tests/compiler/c0/run-rv64-integer-aggregate-return.sh
sh tests/compiler/c0/run-unnamed-bit-fields.sh
sh tests/compiler/c0/run-gnu-overflow-builtins.sh
sh tests/compiler/c0/run-gnu-register-inline-asm-output.sh
sh tests/compiler/c0/run-function-linkage-inheritance.sh
sh tests/compiler/c0/run-static-prefix-object-attributes.sh
sh tests/compiler/c0/run-extern-incomplete-record-object.sh
sh tests/compiler/c0/run-extern-function-pointer-object.sh
sh tests/compiler/c0/run-extern-interleaved-function-attributes.sh
sh tests/compiler/c0/run-shared-function-declarator.sh
sh tests/compiler/c0/run-enum-tag-type-references.sh
sh tests/compiler/c0/run-extern-multi-declarators.sh
sh tests/compiler/c0/run-extern-multidimensional-array.sh
sh tests/compiler/c0/run-gnu-extern-object-redeclaration.sh
sh tests/compiler/c0/run-gnu-section-symbol-attribute.sh
sh tests/compiler/c0/run-gnu-const-function-attribute.sh
sh tests/compiler/c0/run-gnu-octal-character-case-range.sh
