from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file_path = Path(path)
    text = file_path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one anchor, found {count}")
    file_path.write_text(text.replace(old, new, 1))


replace_once(
    "src/frontend/ast.c",
    """bool minic_c0_record_value_is_copy_source(const MinicC0Program *program,\n                                          MinicExpressionId expression_id) {\n    const MinicExpression *expression;\n\n    if (program == NULL) {\n        return false;\n    }\n    if (minic_c0_record_value_is_address_backed(program, expression_id)) {\n        return true;\n    }\n    expression = minic_c0_program_expression(program, expression_id);\n    return expression != NULL && expression->kind == MINIC_EXPRESSION_CALL &&\n           expression->value_category == MINIC_VALUE_RVALUE &&\n           minic_type_is_record(expression->type);\n}\n""",
    """static bool minic_c0_record_value_is_copy_source_bounded(const MinicC0Program *program,\n                                                          MinicExpressionId expression_id,\n                                                          size_t remaining) {\n    const MinicExpression *expression;\n\n    if (program == NULL || remaining == 0U) {\n        return false;\n    }\n    if (minic_c0_record_value_is_address_backed(program, expression_id)) {\n        return true;\n    }\n    expression = minic_c0_program_expression(program, expression_id);\n    if (expression == NULL || expression->value_category != MINIC_VALUE_RVALUE ||\n        !minic_type_is_record(expression->type)) {\n        return false;\n    }\n    if (expression->kind == MINIC_EXPRESSION_CALL) {\n        return true;\n    }\n    if (expression->kind == MINIC_EXPRESSION_CONDITIONAL) {\n        const MinicExpression *when_true;\n        const MinicExpression *when_false;\n        MinicExpressionId when_true_id;\n        MinicExpressionId when_false_id;\n\n        if (expression->value.conditional.uses_condition_value) {\n            return false;\n        }\n        when_true_id = expression->value.conditional.when_true;\n        when_false_id = expression->value.conditional.when_false;\n        if (when_true_id >= expression_id || when_false_id >= expression_id) {\n            return false;\n        }\n        when_true = minic_c0_program_expression(program, when_true_id);\n        when_false = minic_c0_program_expression(program, when_false_id);\n        return when_true != NULL && when_false != NULL &&\n               minic_type_is_record(when_true->type) && minic_type_is_record(when_false->type) &&\n               when_true->type.record_id == expression->type.record_id &&\n               when_false->type.record_id == expression->type.record_id &&\n               minic_c0_record_value_is_copy_source_bounded(\n                   program, when_true_id, remaining - 1U) &&\n               minic_c0_record_value_is_copy_source_bounded(\n                   program, when_false_id, remaining - 1U);\n    }\n    return false;\n}\n\nbool minic_c0_record_value_is_copy_source(const MinicC0Program *program,\n                                          MinicExpressionId expression_id) {\n    if (program == NULL || program->expression_count == SIZE_MAX) {\n        return false;\n    }\n    return minic_c0_record_value_is_copy_source_bounded(\n        program, expression_id, program->expression_count + 1U);\n}\n""",
)

replace_once(
    "src/target/riscv64/codegen_expression.c",
    """    if (source->kind == MINIC_EXPRESSION_CALL) {\n        MinicRiscv64AbiValue value;\n""",
    """    if (source->kind == MINIC_EXPRESSION_CONDITIONAL) {\n        const MinicExpression *condition;\n        const MinicExpression *when_true;\n        const MinicExpression *when_false;\n\n        condition = minic_c0_program_expression(program, source->value.conditional.condition);\n        when_true = minic_c0_program_expression(program, source->value.conditional.when_true);\n        when_false = minic_c0_program_expression(program, source->value.conditional.when_false);\n        if (source->value.conditional.uses_condition_value || condition == NULL ||\n            when_true == NULL || when_false == NULL || !type_is_condition_scalar(condition->type) ||\n            !minic_type_is_record(when_true->type) || !minic_type_is_record(when_false->type) ||\n            when_true->type.record_id != source->type.record_id ||\n            when_false->type.record_id != source->type.record_id ||\n            !minic_c0_record_value_is_copy_source(program, source->value.conditional.when_true) ||\n            !minic_c0_record_value_is_copy_source(program, source->value.conditional.when_false) ||\n            !minic_riscv64_emit_expression(\n                file, program, function, function_layout, source->value.conditional.condition) ||\n            fprintf(file, \"  beqz a0, .Lminic_record_cond_false_%zu\\n\", source_id) < 0 ||\n            !minic_riscv64_emit_record_value_temporary(file,\n                                                       program,\n                                                       function,\n                                                       function_layout,\n                                                       source->value.conditional.when_true,\n                                                       storage_size,\n                                                       temporary_size) ||\n            fprintf(file,\n                    \"  j .Lminic_record_cond_end_%zu\\n\"\n                    \".Lminic_record_cond_false_%zu:\\n\",\n                    source_id,\n                    source_id) < 0 ||\n            !minic_riscv64_emit_record_value_temporary(file,\n                                                       program,\n                                                       function,\n                                                       function_layout,\n                                                       source->value.conditional.when_false,\n                                                       storage_size,\n                                                       temporary_size)) {\n            return false;\n        }\n        return fprintf(file, \".Lminic_record_cond_end_%zu:\\n\", source_id) >= 0;\n    }\n    if (source->kind == MINIC_EXPRESSION_CALL) {\n        MinicRiscv64AbiValue value;\n""",
)

Path("tests/compiler/c0/record_conditional_materialization.c").write_text(
    """typedef struct {\n    unsigned long bits;\n} pgprot_t;\n\nstatic pgprot_t pgprot_from_va(unsigned long value) {\n    return (pgprot_t){value + 1UL};\n}\n\nstatic unsigned long consume(pgprot_t value) {\n    return value.bits;\n}\n\nstatic unsigned long assign_then_read(int early, unsigned long value) {\n    pgprot_t selected;\n\n    selected = early ? (pgprot_t){7UL} : pgprot_from_va(value);\n    return selected.bits;\n}\n\nint main(void) {\n    if (consume(1 ? (pgprot_t){3UL} : pgprot_from_va(10UL)) != 3UL) {\n        return 1;\n    }\n    if (consume(0 ? (pgprot_t){3UL} : pgprot_from_va(10UL)) != 11UL) {\n        return 2;\n    }\n    if (assign_then_read(0, 20UL) != 21UL) {\n        return 3;\n    }\n    return assign_then_read(1, 20UL) == 7UL ? 0 : 4;\n}\n"""
)

Path("tests/compiler/c0/run-record-conditional-materialization.sh").write_text(
    """#!/bin/sh\nset -eu\n\nroot=$(CDPATH= cd -- \"$(dirname -- \"$0\")/../../..\" && pwd)\nminic=${MINIC:-\"$root/build/debug/bin/minic\"}\nhost_cc=${HOST_CC:-${CC:-cc}}\nwork=${BUILD_DIR:-\"$root/build/debug\"}/tests/record-conditional-materialization\n\nmkdir -p \"$work\"\n\n\"$host_cc\" -E -P -std=gnu11 -x c \\\n    \"$root/tests/compiler/c0/record_conditional_materialization.c\" \\\n    -o \"$work/input.i\"\n\"$minic\" -S \"$work/input.i\" -o \"$work/output.s\"\n\ngrep -F '.Lminic_record_cond_false_' \"$work/output.s\" >/dev/null\ngrep -F '.Lminic_record_cond_end_' \"$work/output.s\" >/dev/null\ngrep -F '  call pgprot_from_va' \"$work/output.s\" >/dev/null\ngrep -F '  call consume' \"$work/output.s\" >/dev/null\n\nif command -v riscv64-linux-gnu-gcc >/dev/null 2>&1; then\n    riscv64-linux-gnu-gcc -c \"$work/output.s\" -o \"$work/output.o\"\nfi\n\nprintf '%s\\n' 'PASS compiler/c0/record_conditional_materialization record-rvalue=conditional producers=address,call sink=assignment,call-argument'\n"""
)

run_path = Path("tests/compiler/c0/run.sh")
run_text = run_path.read_text()
anchor = '''MINIC="$minic" \\\nHOST_CC="$host_cc" \\\nBUILD_DIR="${BUILD_DIR:-"$root/build/debug"}" \\\nsh "$root/tests/compiler/c0/run-record-rvalue-member.sh"\n'''
addition = anchor + '''\nMINIC="$minic" \\\nHOST_CC="$host_cc" \\\nBUILD_DIR="${BUILD_DIR:-"$root/build/debug"}" \\\nsh "$root/tests/compiler/c0/run-record-conditional-materialization.sh"\n'''
if run_text.count(anchor) != 1:
    raise SystemExit(f"tests/compiler/c0/run.sh: expected one record-rvalue anchor, found {run_text.count(anchor)}")
run_path.write_text(run_text.replace(anchor, addition, 1))
