#!/usr/bin/env python3
"""Reproduce pinned performance-branch Parser deltas in a disposable checkout.

Production runtime sources remain unmodified. Each replacement must have
exactly one old-context match, or the candidate fails closed.
"""
from pathlib import Path

p = Path("src/frontend/parser_core.c")
s = p.read_text()
old = "MinicFunctionId minic_parser_find_function(const MinicParser *parser, MinicSourceSpan name_span) {\n    size_t name_length;\n    size_t index;\n\n    name_length = minic_parser_span_length(name_span);\n    for (index = 0U; index < parser->program->function_count; ++index) {\n        const MinicFunction *function;\n\n        function = minic_c0_program_function(parser->program, index);\n        if (function != NULL && function->name_length == name_length &&\n            memcmp(function->name, parser->source + name_span.begin.offset, name_length) == 0) {\n            return index;\n        }\n    }\n    return MINIC_FUNCTION_INVALID;\n}\n\n"
new = "MinicFunctionId minic_parser_find_function(const MinicParser *parser, MinicSourceSpan name_span) {\n    size_t name_length;\n    size_t index;\n\n    name_length = minic_parser_span_length(name_span);\n    for (index = parser->program->function_count; index > 0U; --index) {\n        size_t function_index = index - 1U;\n        const MinicFunction *function;\n\n        function = minic_c0_program_function(parser->program, function_index);\n        if (function != NULL && function->name_length == name_length &&\n            memcmp(function->name, parser->source + name_span.begin.offset, name_length) == 0) {\n            return function_index;\n        }\n    }\n    return MINIC_FUNCTION_INVALID;\n}\n\n"
if s.count(old) != 1:
    raise SystemExit(f"PERF_PARSER_OVERLAY_ANCHOR_MISMATCH: {p}")
p.write_text(s.replace(old, new, 1))

p = Path("src/frontend/parser_global.c")
s = p.read_text()
old = "MinicGlobalObjectId minic_parser_find_global_object_entity(const MinicParser *parser,\n                                                           MinicSourceSpan name_span) {\n    size_t name_length;\n    size_t index;\n\n    if (parser == NULL || parser->program == NULL) {\n        return MINIC_GLOBAL_OBJECT_INVALID;\n    }\n    name_length = minic_parser_span_length(name_span);\n    for (index = 0U; index < parser->program->global_object_count; ++index) {\n        const MinicGlobalObject *object;\n\n        object = minic_c0_program_global_object(parser->program, index);\n        if (object != NULL && object->name_length == name_length &&\n            memcmp(object->name, parser->source + name_span.begin.offset, name_length) == 0) {\n            return index;\n        }\n    }\n    return MINIC_GLOBAL_OBJECT_INVALID;\n}\n\n"
new = "MinicGlobalObjectId minic_parser_find_global_object_entity(const MinicParser *parser,\n                                                           MinicSourceSpan name_span) {\n    size_t name_length;\n    size_t index;\n\n    if (parser == NULL || parser->program == NULL) {\n        return MINIC_GLOBAL_OBJECT_INVALID;\n    }\n    name_length = minic_parser_span_length(name_span);\n    for (index = parser->program->global_object_count; index > 0U; --index) {\n        size_t object_index = index - 1U;\n        const MinicGlobalObject *object;\n\n        object = minic_c0_program_global_object(parser->program, object_index);\n        if (object != NULL && object->name_length == name_length &&\n            memcmp(object->name, parser->source + name_span.begin.offset, name_length) == 0) {\n            return object_index;\n        }\n    }\n    return MINIC_GLOBAL_OBJECT_INVALID;\n}\n\n"
if s.count(old) != 1:
    raise SystemExit(f"PERF_PARSER_OVERLAY_ANCHOR_MISMATCH: {p}")
p.write_text(s.replace(old, new, 1))

p = Path("src/frontend/parser_expression.c")
s = p.read_text()
old = "        name_span = parser->current.span;\n        local_id = minic_parser_find_local(parser, name_span);\n        function_id = minic_parser_find_function(parser, name_span);\n        global_object_id = minic_parser_find_global_object(parser, name_span);\n        fixed_register_binding_id = minic_parser_find_fixed_register_binding(parser, name_span);\n        enumerator_id = minic_parser_find_enum_constant(parser, name_span);\n        if (!minic_parser_advance(parser)) {\n            return false;\n        }\n\n        if (parser->current.kind == MINIC_TOKEN_LPAREN && local_id == MINIC_LOCAL_INVALID &&\n            function_id != MINIC_FUNCTION_INVALID) {\n            MinicSourcePosition call_end;\n            const MinicFunction *callee;\n\n            callee = minic_c0_program_function(parser->program, function_id);\n            if (callee == NULL || callee->parameter_count > MINIC_MAX_FUNCTION_PARAMETERS ||\n                !minic_c0_program_set_function_referenced(parser->program, function_id, true) ||\n                !minic_parser_advance(parser)) {\n                minic_parser_error(parser, \"unsupported function call signature\");\n                return false;\n            }\n\n            (void)memset(&expression, 0, sizeof(expression));\n            expression.kind = MINIC_EXPRESSION_CALL;\n            expression.span.begin = name_span.begin;\n            expression.type = callee->return_type;\n            expression.value_category = MINIC_VALUE_RVALUE;\n            expression.value.call.function_id = function_id;\n            if (!parse_call_arguments(parser, &expression, callee)) {\n                return false;\n            }\n            call_end = parser->current.span.end;\n            if (!minic_parser_advance(parser)) {\n                return false;\n            }\n            expression.span.end = call_end;\n            if (!minic_parser_add_expression(parser, &expression, &primary_id) ||\n                !minic_parser_parse_postfix(parser, primary_id, &primary_id)) {\n                return false;\n            }\n            return finish_value_expression(parser, primary_id, decay_array, expression_id);\n        }\n\n        if (local_id != MINIC_LOCAL_INVALID) {\n            if (!parse_local_reference(parser, name_span, local_id, &primary_id)) {\n                return false;\n            }\n            return finish_value_expression(parser, primary_id, decay_array, expression_id);\n        }\n"
new = "        name_span = parser->current.span;\n        local_id = minic_parser_find_local(parser, name_span);\n        if (local_id != MINIC_LOCAL_INVALID) {\n            if (!minic_parser_advance(parser) ||\n                !parse_local_reference(parser, name_span, local_id, &primary_id)) {\n                return false;\n            }\n            return finish_value_expression(parser, primary_id, decay_array, expression_id);\n        }\n\n        function_id = minic_parser_find_function(parser, name_span);\n        if (!minic_parser_advance(parser)) {\n            return false;\n        }\n\n        if (parser->current.kind == MINIC_TOKEN_LPAREN &&\n            function_id != MINIC_FUNCTION_INVALID) {\n            MinicSourcePosition call_end;\n            const MinicFunction *callee;\n\n            callee = minic_c0_program_function(parser->program, function_id);\n            if (callee == NULL || callee->parameter_count > MINIC_MAX_FUNCTION_PARAMETERS ||\n                !minic_c0_program_set_function_referenced(parser->program, function_id, true) ||\n                !minic_parser_advance(parser)) {\n                minic_parser_error(parser, \"unsupported function call signature\");\n                return false;\n            }\n\n            (void)memset(&expression, 0, sizeof(expression));\n            expression.kind = MINIC_EXPRESSION_CALL;\n            expression.span.begin = name_span.begin;\n            expression.type = callee->return_type;\n            expression.value_category = MINIC_VALUE_RVALUE;\n            expression.value.call.function_id = function_id;\n            if (!parse_call_arguments(parser, &expression, callee)) {\n                return false;\n            }\n            call_end = parser->current.span.end;\n            if (!minic_parser_advance(parser)) {\n                return false;\n            }\n            expression.span.end = call_end;\n            if (!minic_parser_add_expression(parser, &expression, &primary_id) ||\n                !minic_parser_parse_postfix(parser, primary_id, &primary_id)) {\n                return false;\n            }\n            return finish_value_expression(parser, primary_id, decay_array, expression_id);\n        }\n\n        global_object_id = minic_parser_find_global_object(parser, name_span);\n        fixed_register_binding_id = minic_parser_find_fixed_register_binding(parser, name_span);\n        enumerator_id = minic_parser_find_enum_constant(parser, name_span);\n\n"
if s.count(old) != 1:
    raise SystemExit(f"PERF_PARSER_OVERLAY_ANCHOR_MISMATCH: {p}")
p.write_text(s.replace(old, new, 1))

print("MINIC_PERF_SOURCE_OVERLAY=PASS files=3")
